FROM python:3

RUN set -x && \
  apt-get update && \
  apt-get install -y vim && \
  pip install selenium && \
  pip install PyDrive && \ 
  pip install google-api-python-client && \
  pip install google-auth && \
  pip install google-auth-httplib2 && \
  pip install httplib2 && \
  pip install nose && \
  pip install oauth2client && \
  pip install gspread