client_config_backend: settings
client_config:
  client_id: 903912358690-ilbaoagb74o7v9rkl3svnp5nm4hegpnu.apps.googleusercontent.com
  client_secret: WefYUb_vU6fTsWsJsdOQuVE2

save_credentials: True
save_credentials_backend: file
save_credentials_file: gdrive_oauth2_credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install